# Site menu (partial -- also see pages with 'menu' in front matter)
main:
  - name: Docs
    url: /docs/latest/
    weight: -10
  - name: Blog
    pageref: /blog/
  - name: Install
    url: /docs/latest/install/
  - name: Play
    url: http://play.etcd.io/play
